### ISSUE TITLE
Following error is occurring.. how to resolve 

### ISSUE THREAD

**Issue by namanjainn** [goxr3plus/Java-Speech-Recognizer-Tutorial--Calculator#1]
Jan 18, 2017 5:24:41 PM model.Main <init>
INFO: Loading..

Exception in thread "main" Property exception component:'jsgfGrammar' property:'grammarLocation' - Can't locate resource:/grammars
edu.cmu.sphinx.util.props.InternalConfigurationException: Can't locate resource:/grammars
	at edu.cmu.sphinx.util.props.ConfigurationManagerUtils.getResource(ConfigurationManagerUtils.java:468)
	at edu.cmu.sphinx.jsgf.JSGFGrammar.newProperties(JSGFGrammar.java:228)
	at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
	at edu.cmu.sphinx.util.props.PropertySheet.getComponent(PropertySheet.java:296)
	at edu.cmu.sphinx.linguist.flat.FlatLinguist.newProperties(FlatLinguist.java:222)
	at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
	at edu.cmu.sphinx.util.props.PropertySheet.getComponent(PropertySheet.java:296)
	at edu.cmu.sphinx.decoder.search.SimpleBreadthFirstSearchManager.newProperties(SimpleBreadthFirstSearchManager.java:177)
	at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
	at edu.cmu.sphinx.util.props.PropertySheet.getComponent(PropertySheet.java:296)
	at edu.cmu.sphinx.decoder.AbstractDecoder.newProperties(AbstractDecoder.java:81)
	at edu.cmu.sphinx.decoder.Decoder.newProperties(Decoder.java:36)
	at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
	at edu.cmu.sphinx.util.props.PropertySheet.getComponent(PropertySheet.java:296)
	at edu.cmu.sphinx.recognizer.Recognizer.newProperties(Recognizer.java:86)
	at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:518)
	at edu.cmu.sphinx.util.props.ConfigurationManager.lookup(ConfigurationManager.java:163)
	at edu.cmu.sphinx.api.Context.<init>(Context.java:73)
	at edu.cmu.sphinx.api.Context.<init>(Context.java:45)
	at edu.cmu.sphinx.api.AbstractSpeechRecognizer.<init>(AbstractSpeechRecognizer.java:44)
	at edu.cmu.sphinx.api.LiveSpeechRecognizer.<init>(LiveSpeechRecognizer.java:34)
	at model.Main.<init>(Main.java:55)
	at model.Main.main(Main.java:165)

**Comment by namanjainn** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/10618719/22063292/16717aac-dda4-11e6-8dea-faa3ac08f104.PNG)
I have followed the steps: attaching screenshot to showcase directory structure of the project

**Comment by goxr3plus** [comment]
Hello mamanjain . If you look closely at the video tutorials you can see that the `resources` folder is actually a package folder along with `src` folder so (below is a similar project in which i am using `Sphinx` : 

🍒You go right click on the project [`SimpleSpeechRecog`] and create a package name it `resources` etc.... inside it create the packages `grammars` and `libraries`.

The right click:
-----------------------------------------------------

![screenshot28287](https://cloud.githubusercontent.com/assets/20374208/22090623/8cbd03e6-ddfb-11e6-8a40-f2f496183bc3.png)


Image from similar project:
-----------------------------------------------------

![screenshot9386](https://cloud.githubusercontent.com/assets/20374208/22090624/90484c0a-ddfb-11e6-86c5-dc2e6122efa8.png)

**Comment by amyrick** [comment]
i also get the same issue how i resolve it ?
give an any idea sir?...

**Comment by goxr3plus** [comment]
@amyrick  The answer is above . Please read carefully and it will resolve your problem :) .
                 You can see that `**resources**` is a `**Package Folder**` not just a folder outside of the Project . That's a common misconception , though i have shown it on the tutorial .

**Comment by amyrick** [comment]
Thanku so Much sir , using netbeans i done it .

On May 25, 2017 6:19 AM, "GOXR3PLUS STUDIO" <notifications@github.com>
wrote:

@amyrick <https://github.com/amyrick> I have added the answer , it is above
. Please read carefully and it will resolve your problem :) .
You can see that resources is a Resource Folder not just a folder outside
of the Project . That's a common missconception , though i have shown it on
the tutorial .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/goxr3plus/Java-Speech-Recognizer-Tutorial--Calculator/issues/1#issuecomment-303892152>,
or mute the thread

**Comment by goxr3plus** [comment]
@namanjainn  @amyrick  Guys is this error resolved should i close the issue :) ?
