### ISSUE TITLE
Configuration class not found error in Eclipse

### ISSUE THREAD

**Issue by shravilgupta** [goxr3plus/Java-Speech-Recognizer-Tutorial--Calculator#10]
Hi Alex i followed the tutorial 1 exactly as guided in the youtube video. the build is successful without errors. But when i run the Main java file it gives me the following error:

Exception in thread "main" java.lang.NoClassDefFoundError: edu/cmu/sphinx/api/Configuration
 at model.SpeechRecognizerMain.main(SpeechRecognizerMain.java:15)
Caused by: java.lang.ClassNotFoundException: edu.cmu.sphinx.api.Configuration
 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
 ... 1 more

Please guide.

Thanks in advance.

**Comment by goxr3plus** [comment]
Have you added all the libraries in the project path and imported them with Eclipse :)

I neec to add Maven or Gradle for this project so the users don't have to worry about dependencies mmm

**Comment by shravilgupta** [comment]
Yes i did. Just as you had shown in video. Added folder named 'libraries' copied the sphinx jars there. Then using build path option i setup the jars for project. 

Yeah it would be of great help if you can add Maven for the project.

**Comment by shravilgupta** [comment]
(https://user-images.githubusercontent.com/12764528/62921287-f2218200-bdc5-11e9-95a9-44af8750206f.JPG)
(https://user-images.githubusercontent.com/12764528/62921289-f2218200-bdc5-11e9-9eac-0dc7498e8054.JPG)
